language: minimal
sudo: required
dist: xenial
install:
  - docker build -q -t android-build .
  - docker run --rm -v "$PWD":/home/gradle/ -w /home/gradle/ android-build gradle assemble
env:
  global:
    - secure: tEbGzoQvyNSIio0Rf2MAoGnZmLlW5tYhPlAUb9lZV9erJUFkfWS/cM356bTNQwlkENQ2eVD1BqxC2WFHvGeIQB2s2pJXKFn1yQdRKhQH7++OUMqwjaO+L/cI5m5zmUqZKop9JgBbq/hadV57ubvXWD7bdwrjQ0ip+hfQI+syH2vmLrbZI6cgQRtNlWKXYZ207HCs8kDAm9Bma1kWPbNG7CQtY626Hi1aj9cBc1p3G1Ywt5eUKcNodndoKfDp1fNHwDFekYOOhjnsgikvg7VDaWU160d3n3d27EhUsWYYcHbCjCRz3ywcpAn8blXzb59BR/wKTgkVzk5LhFETyhDsOMe02EG78z49cmaUhG/xZY5utiErc4PmAGF1jpJfuijh7s7YNDaGw4fhW2+mo6RLVa1ZcAaF4YAe9CPxgXwr79DvinBBoK8YMBAr30nf6bSz9HHk6TLt6M3vxKxe9veHD7TFHhAHe72A75NYAUFauMSP7Oi5ucmNRmpBdhfKrFZUKae6CPDNpKaykTXaq+V/iYhXjbo4qrVNn3EvBe7f9uEK/Cm73E6Qx7mlF35TabWJmCyi8MNkYDvHExsKP0W+NRF3w936dxH5R1/PgkhwvYZG1F6Oj52GO0wwRB9y7ebzHo/WodRxyLP/SAGnRpDXVuUi2BybqxhuISoIyzm1enc=
    - secure: tcpDIbclJnQAfboTQVFSM04pYPP8Do8oiumBaiECEKerQmEh+oLSPz8e/zPunOL9eOkJedblMCu5ipTbQFKMN66+BwtAybkr4hMfVRkvYiCC4pIyDtWm2jLGQh9jZZNsgp8L+incfYtDmst4SNZWVRRwtXp57U6InArxaTaeHwToZ9rXTkO7qaHSFII8r8fA01EngDjHfD9gaPIU99V6DD4CxwtiEpXkViUp4I6rOeXs93vU1MRl6Cip6eL8o+mkV9lD+K+oMqMZqEMurQ1tD2geDhYgLKl4lNE6T1Lmx19cUul6tsYA2f2/ftX8Xpf8tRzomgj+pEe2RvLMSsnmeprM5LSmfijjcshhE61dF20Wa+TB6VSti5iHRYfVnHTG4BQgGhGIFXFCebWIEC/EhcevM6RpIEiOzNvD5P14c7SAwyjHVzzC068HVvpVhbNSYhkXOy+GqOWYlMM1PTMPVcpqV+zuH9MLo0rk2xD/SdAFny4Sm3T2PmNx0NmkNhAEEHGBIpE+AXVBB8AFX/84wquD1hthW/8ZSvyesJlE58NBbpqideFY9YfRW7GsFYl6ACiyjzqirV63HcjPpoc57mLWynJytNDvnS/K9g/JXcV5xxWmJcUoiXzKj8dZvmxZ0sJi6gWYqEgm/vmYHwKXAZ29kUELVxaaeW8CLFnpwD4=
    - secure: kynKk+hyDv2o+TK/7DSVrxk/Zw1DeC4wZAuoxtVCONnDrkUfiKoOqXw6QF5kHjJ52GDvbWJjsKKu8j7tXH5cpqTq0P2C6Lanon9vIRfWctmX95j8qPyGN1ZQFzzP0XQVmULKcIqlmyLGCeIBrzESyC8oTKIJUAVzPfd/EFgq7jKdigfR9HXcAWI/EHlMEB35DN0YMJodnMdkzI6FP0Ta6ySk40I1WRPnAvH+XrHibCMkLdnl4uvQuWiVd4TZZWMHMSBe6+6H++TI7mrAUVC1yAZmnnK/u5dm2LNQVPVT9p8QKEdG5XzYIEhZhQ7hm+4s7V13zeRH7DJfCh3IBVPQI2a+mko3xHn7KaefVl4EjWLXAuoXDGP8F4GJVsUFV3X37vQe50Egkw/YieJ5/IaRcYko0BdrSRTyed0+R149GHCYCcRyRF0WQH/sBMQVQtMP9MMaRls/vFR+UwvRJRMuht0Y8nj4h3uR3QJ5OCD9yXp4rBUb7uNEbCHq50anUJHH6E7rKwjcp9bSLvRjpgiklCLgpwBZKluiWHgQj8eZkjM97fxAqe05f/hvli5VbZ2vnXJNfMb64hrtJotb0JkVlpHl0bzsXT0TDyPxab2YKraMMdj24xPl7LG954ikgKSGVuiv7WwqqlANbvyzxVR98VkBsXprd0+SHnvUsOMj0Yw=
deploy:
  provider: script
  before_script:
    - openssl aes-256-cbc -K $encrypted_7ca4baf07889_key -iv $encrypted_7ca4baf07889_iv
      -in mewconnect.tar.enc -out ~\/amazon/android/mewconnect.tar -d
    - tar xvf mewconnect.tar
    - gpg --allow-secret-key-import --import mew_sec.gpg
  script: bash ./release.sh $TRAVIS_TAG $GITHUB_TOKEN "kvhnuke/MEWconnect-Android" true
  skip_cleanup: true
  on:
    tags: true
    branch: master
